spring:
  application:
    name: simple-service

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

keycloak:
  auth-server-url: http://127.0.0.1:30000/auth
  realm: company-services
  resource: simple-service
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true
